TEST_VALUE:
  name: dev_cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a8d8c3da04a7500b
  FEISHU_APP_SECRET: k9rhAzTJItf7icrxFYI8bfEJzYGlTmw7

APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY

MONGODB_CONFIG:
  name: 'fast_gateway_test'
  type: mongodb
  url: 'mongodb://localhost:27017'
  username: 'like'
  password: '123456'
  database: 'fast_gatway_test'
  logging: false
  synchronize: true

MYSQL_CONFIG:
  name: 'user-test'
  type: mysql
  url: 'localhost'
  port: 3306
  username: 'like'
  password: '123456'
  database: 'user-test'
  entities: 'mysql'
  synchronize: true

REDIS_CONFIG:
  host: 'localhost'
  port: 6379
  auth: '123456'
  db: 1
  ttl: 7200 # 默认缓存过期时间（秒）
